# Generated by Django 4.1 on 2023-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(unique=True, upload_to='image/%Y/%m/%d')),
                ('description', models.TextField(max_length=2000, unique=True)),
            ],
        ),
    ]
